`# CREATE/POPULATE YOUR ENVIRONMENT VARIABLES
DEBUG="${opts.projectName}:server"

${
  opts.sequelize
    ? `DATABASE_NAME=
DATABASE_USER=
DATABASE_PASSWORD=
DATABASE_HOST=
DATABASE_DIALECT="postgres"
`
    : ``
}
`;
